server:
  port: 8080

spring:
  # Load .env
  config:
    import: optional:file:.env

  application:
    name: Smart Room Finder

  # MySQL
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-init-sql: SELECT 1
      initialization-fail-timeout: 0
      minimum-idle: 5
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GG}
            client-secret: ${CLIENT_SECRET_GG}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic

          facebook:
            client-id: ${CLIENT_ID_FB}
            client-secret: ${CLIENT_SECRET_FB}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: email, public_profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          facebook:
            authorization-uri: https://www.facebook.com/v23.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            user-name-attribute: id

  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:5173
      - http://127.0.0.1:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org:
      springframework:
        security:
          oauth2: TRACE
        web: DEBUG
    com:
      smartroomfinder:
        smartroomfinder: DEBUG
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

app:
  frontend-url: ${FRONTEND_URL}
  backend-url: ${BACKEND_URL}

